version: '3.8'

services:
  postgres-billing:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=billing"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  postgres-notifications:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=notifications"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5433:5432"

  postgres-orders:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=orders"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5434:5432"

  postgres-delivery:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=delivery"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5435:5432"

  postgres-warehouse:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=warehouse"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5436:5432"